#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/
# this file is from https://github.com/jnovack/dockerhub-hooks

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

TAG=`git describe --tag --match "v*"`
FLAVOUR=`echo ${TAG} | awk -F'-' '{print $1}' | awk -F'.' '{print $2}'`

docker build \
    --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --build-arg COMMIT=$(git rev-parse --short HEAD) \
    --build-arg VERSION=$(git describe --tags --always) \
    --target ${FLAVOUR:-defaultuser} \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .